/*********************************************************************
*
*	论坛    :http://www.firebbs.cn
*	淘宝    :http://fire-stm32.taobao.com
*	邮箱	:wildfireteam@163.com
*
*
**********************************************************************
*/
/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include "includes.h"
#include  "app.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/



// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreateUSER[] = {
  { FRAMEWIN_CreateIndirect, "UserApp", 0, 0, 0, 800, 480, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialogUSER(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END
  switch (pMsg->MsgId) {
	  case WM_DELETE:
		    OS_DEBUG("USERApp delete\n");
		    OnICON17 = 0;
			app_prevent_refresh = 0;
	  WM_InvalidateWindow(WM_HBKWIN);
		    break;
	  case WM_INIT_DIALOG:
		//
		// Initialization of 'LED TEST'
		//
	    hItem = pMsg->hWin;
		FRAMEWIN_SetTextColor(hItem, GUI_DARKGRAY);
		FRAMEWIN_SetFont(hItem, GUI_FONT_32B_ASCII);
		FRAMEWIN_SetTitleHeight(hItem, 40);
		FRAMEWIN_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
		FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,0);
        //SLIDER_SetValue(hItem, 500);
		// USER START (Optionally insert additional code for further widget initialization)
		// USER END
		break;
	  // USER START (Optionally insert additional message handling)
		case WM_PAINT:	
			GUI_SetBkColor(APPBKCOLOR);
			GUI_SetColor(APPTEXTCOLOR);
			GUI_Clear();
			GUI_SetFont(&GUI_FontHZ32);
			GUI_DispStringHCenterAt("用户自定义扩展",400,40);
			break;
	  // USER END
	  default:
		WM_DefaultProc(pMsg);
		break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateUSB TEST
*/
void OnICON17Clicked(void)
{

	GUI_CreateDialogBox(_aDialogCreateUSER, GUI_COUNTOF(_aDialogCreateUSER), _cbDialogUSER, WM_HBKWIN, 0, 0);
	OS_DEBUG("USERApp create\n");
	while(OnICON17)
	{					 				
        GUI_Delay(10); 				
	}
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
