/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "includes.h"
#include  "app.h"
#include "sim900a.h"
// USER END

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
// USER START (Optionally insert additional defines)
#define _DF1S	0x81
#define MESS_LIST_PATH 		"0:/system/messagelist.txt"
#define MESSAGE_MAX			30
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
// USER START (Optionally insert additional static data)
extern FIL	file;
extern FRESULT result;
extern UINT bw;	

/*********** 输入法 ********/
extern OS_TCB	AppTaskGuiKeyPadTCB;
extern uint8_t  keyflag;
extern WM_HWIN hKeyPad;
/*************************/

static WM_HWIN hContacts,hMessagelist,hContent,hText;
static uint16_t 	messagesapp[2];
static uint8_t  	messageindex=0;
static uint8_t		messageNumRows=0;
static char pStat[5]   	 ={0};
static char pContacts[20]={0};
static char pContentlist[15]={0};
static char pContent[325]={0};
static uint8_t IsSetList=0;
static const char * _aTable_[1][3] = {0};
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreateMessage[] = {
  { FRAMEWIN_CreateIndirect, "Message", 0, 0, 0, 800, 480, 0, 0x0, 0 },
  { LISTVIEW_CreateIndirect, "MESSAGEList", GUI_ID_LISTVIEW0, 5, 0, 400-15, 440-5, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "To", GUI_ID_TEXT0, 400-5, 5, 120, 40, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "contact", GUI_ID_EDIT0, 520-5, 5, 270, 40, 0, 0x1e, 0 },
  { BUTTON_CreateIndirect, "send", GUI_ID_BUTTON0, 470, 375, 80, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "cancel", GUI_ID_BUTTON1, 640, 375, 80, 50, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "edit", GUI_ID_MULTIEDIT0, 400-5, 50, 395, 310, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
// USER START (Optionally insert additional static code)

static void LISTVIEW_AddItem(void)
{
	uint8_t i=0,j=0;
	messageNumRows=0;
	//result = f_unlink(MESS_LIST_PATH);//删除文件
	//result = f_open (&file, MESS_LIST_PATH,FA_READ|FA_WRITE|FA_CREATE_ALWAYS);
	result = f_open (&file, MESS_LIST_PATH,FA_READ);
	if(result != FR_OK)
	{
		f_close (&file);
		return ;
	}
	while(result == FR_OK && messageNumRows<MESSAGE_MAX)
	{
		result = f_lseek(&file,messageNumRows*325);
		if(result != FR_OK)break;
		//result = f_write(&file,pContent, 325, &bw);
		result = f_read(&file,pContent, 100, &bw);
		if(bw < 25)break;
		memcpy(pStat,pContent,sizeof(char)*5);
		i=0;
		while(i<5)
		{
			if(pStat[i]==0x20)
			{
				pStat[i]='\0';
				break;
			}
			i++;
		}
		memcpy(pContacts,&pContent[5],sizeof(char)*20);
		i=0;
		while(i<20)
		{
			if(pContacts[i]==0x20)
			{
				pContacts[i]='\0';
				break;
			}
			i++;
		}
		memcpy(pContentlist,&pContent[25],sizeof(char)*12);
		i=0;
		while(i<12)
		{
			if((uint8_t)pContacts[i]<0x80)
			{
				j++;
			}
			i++;
		}
		if(j==0||j%2)pContentlist[12]='\0';
			else pContentlist[11]='\0';
//		printf("message:%d ::%s::%s::%s\r\n",messageNumRows,pStat,pContacts,pContentlist);
		_aTable_[0][0]=pStat;
		_aTable_[0][1]=pContacts;
		_aTable_[0][2]=pContentlist;
		LISTVIEW_AddRow(hMessagelist, _aTable_[0]);
		messageNumRows++;
	}
	f_close (&file);
}

static void EditMessage(uint8_t index)
{
	uint16_t i=0;
	OS_ERR      err;
	//char contentedit[300]={0};
	result = f_open(&file, MESS_LIST_PATH,FA_READ);
	if(result != FR_OK)
	{
		f_close (&file);
		return ;
	}
	OSSchedLock(&err);
	result = f_lseek(&file,index*325);
	result = f_read(&file,pContent, 325, &bw);
	if(result == FR_OK)
	{
		memcpy(pContacts,&pContent[5],sizeof(char)*20);
		i=0;
		while(i<20)
		{
			if(pContacts[i]==0x20)
			{
				pContacts[i]='\0';
				break;
			}
			i++;
		}
	}
	else
	{
		pContacts[0]='\0';
		pContent[0]='\0';
	}
	OSSchedUnlock(&err);
	f_close (&file);
}

static void SaveMessage(uint8_t index)
{
	OS_ERR      err;
	char contentedit[300]={0};
	uint16_t length=0;
	length=MULTIEDIT_GetTextSize(hContent);
	sprintf(pStat,"%s","To");
	EDIT_GetText(hContacts,pContacts,20);

	result=f_open(&file,MESS_LIST_PATH,FA_WRITE);
	if(result==FR_NO_FILE)
	{
		result=f_open(&file,MESS_LIST_PATH,FA_CREATE_NEW|FA_WRITE);
		messageindex=0;
		index=0;
	}
	result = f_lseek(&file,index*325);
	OSSchedLock(&err);
	MULTIEDIT_GetText(hContent,contentedit,length);
	sprintf(pContent,"%-5s%-20s%s",pStat,pContacts,contentedit);
	result = f_write(&file, pContent, 325, &bw);
	OSSchedUnlock(&err);
	f_close(&file);  
}

void SendMessage(void)
{
	uint16_t MessageLen;
	char contentedit[300]={0};
	MessageLen=MULTIEDIT_GetTextSize(hContent);
	EDIT_GetText(hContacts,pContacts,20);
	MULTIEDIT_GetText(hContent,contentedit,MessageLen);	
	sim900a_sms(pContacts,contentedit);
	//sim900a_sms_utf8(pContacts,contentedit,strlen(pContacts),MessageLen);
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialogMessage(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	OS_ERR      	err;
	uint8_t i=0;
  // USER END

  switch (pMsg->MsgId) {
	case WM_DELETE:
		OS_DEBUG("Messageapp delete\n");
		RCC_APB1PeriphClockCmd(RCC_APB1Periph_USART2, DISABLE);
		USART_ITConfig(USART2, USART_IT_RXNE, DISABLE);	
		USART_Cmd(USART2, DISABLE);
		pContacts[0]='\0';
		pContent[0]='\0';
		messageindex=0;
		messageNumRows=0;
		WM_DeleteWindow(hKeyPad);
		app_prevent_refresh = 0;
		OnICON11 = 0;
	break;
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Message'
    //
    hItem = pMsg->hWin;
	FRAMEWIN_SetTextColor(hItem,GUI_DARKGRAY);
    FRAMEWIN_SetFont(hItem, GUI_FONT_32B_ASCII);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,0);
    FRAMEWIN_SetTitleHeight(hItem, 40);
	//
	// Initialization of 'TO'
	//
	hText = WM_GetDialogItem(pMsg->hWin, GUI_ID_TEXT0);
	TEXT_SetTextColor(hText, GUI_BLUE);
	TEXT_SetTextAlign(hText, GUI_TA_HCENTER | GUI_TA_VCENTER);
	TEXT_SetFont(hText, &GUI_FontHZ24);
	TEXT_SetText(hText, "收件人:");
	//
    // Initialization of 'contacts'
    //
    hContacts = WM_GetDialogItem(pMsg->hWin, GUI_ID_EDIT0);
    EDIT_SetFont(hContacts, GUI_FONT_32B_ASCII);
	EDIT_EnableBlink(hContacts,500,1);
	//
	// Initialization of 'send'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON0);		
	BUTTON_SetText(hItem,"Send");
	BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
	//
	// Initialization of 'cancel'
	//
	hItem = WM_GetDialogItem(pMsg->hWin, GUI_ID_BUTTON1);
	BUTTON_SetText(hItem,"Cannel");
	BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
	//
    // Initialization of 'Content'
    //
    hContent = WM_GetDialogItem(pMsg->hWin, GUI_ID_MULTIEDIT0);
	MULTIEDIT_SetFont(hContent,&GUI_FontHZ24);
	MULTIEDIT_EnableBlink(hContent,500,1);
	MULTIEDIT_SetAutoScrollV(hContent,1);
	MULTIEDIT_SetInsertMode(hContent,1);
	//MULTIEDIT_SetReadOnly(hedit,1);
	MULTIEDIT_SetWrapWord(hContent);
    //
    // Initialization of 'MESSAGEList'
    //
    hMessagelist = WM_GetDialogItem(pMsg->hWin, GUI_ID_LISTVIEW0);
	hItem = LISTVIEW_GetHeader(hMessagelist);
    HEADER_SetFont(hItem,GUI_FONT_24B_ASCII);
    LISTVIEW_AddColumn(hMessagelist, 85, "Stats", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hMessagelist, 140, "Contacts", GUI_TA_HCENTER | GUI_TA_VCENTER);
    LISTVIEW_AddColumn(hMessagelist, 160, "Content", GUI_TA_HCENTER | GUI_TA_VCENTER);
	LISTVIEW_SetGridVis(hMessagelist, 1);
    LISTVIEW_SetFont(hMessagelist, &GUI_FontHZ24);
    LISTVIEW_SetHeaderHeight(hMessagelist, 30);
    LISTVIEW_SetAutoScrollV(hMessagelist, 1);
	LISTVIEW_SetRowHeight(hMessagelist, 30);
	LISTVIEW_SetTextAlign(hMessagelist,0,GUI_TA_HCENTER | GUI_TA_VCENTER);
	LISTVIEW_SetTextAlign(hMessagelist,1,GUI_TA_HCENTER | GUI_TA_VCENTER);
	LISTVIEW_SetTextAlign(hMessagelist,2,GUI_TA_LEFT | GUI_TA_VCENTER);
    // USER START (Optionally insert additional code for further widget initialization)
	LISTVIEW_AddItem();	
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case GUI_ID_LISTVIEW0: // Notifications sent by 'MESSAGEList'
		  switch(NCode) 
		  {
			  case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				//printf("sel:%d\n",messageindex);	
				IsSetList=1;
				// USER END
				break;
			  case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				messageindex=LISTVIEW_GetSel(hMessagelist);
				EditMessage(messageindex);
				WM_HasFocus(hContacts);
				EDIT_SetText(hContacts,pContacts);
				WM_HasFocus(hContent);
				MULTIEDIT_SetText(hContent,&pContent[25]);
				// USER END
				break;
			  case WM_NOTIFICATION_SEL_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
				break;
			  // USER START (Optionally insert additional code for further notification handling)
			  // USER END
		  }
      break;
	  case GUI_ID_EDIT0: // Notifications sent by 'name'
		switch(NCode) 
		{
			case WM_NOTIFICATION_CLICKED:
				// USER START (Optionally insert code for reacting on notification message)
				messagesapp[0]=hContacts;
				messagesapp[1]=GUI_ID_EDIT0;
				if(!keyflag)OSTaskQPost(&AppTaskGuiKeyPadTCB,
						(void *)&messagesapp,
						2,
						OS_OPT_POST_FIFO,
						&err);
				// USER END
			break;
			case WM_NOTIFICATION_RELEASED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
			break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				// USER START (Optionally insert code for reacting on notification message)
				// USER END
			break;
				// USER START (Optionally insert additional code for further notification handling)
				// USER END
		}
      break;
	  case GUI_ID_MULTIEDIT0: // Notifications sent by 'content'
		switch(NCode) 
		{
		  case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			messagesapp[0]=hContent;
			messagesapp[1]=GUI_ID_MULTIEDIT0;
			if(!keyflag)OSTaskQPost(&AppTaskGuiKeyPadTCB,
						(void *)&messagesapp,
						2,
						OS_OPT_POST_FIFO,
						&err);
			// USER END
			break;
		  case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		  case WM_NOTIFICATION_VALUE_CHANGED:
			// USER START (Optionally insert code for reacting on notification message)
			// USER END
			break;
		  // USER START (Optionally insert additional code for further notification handling)
		  // USER END
		}
      break;
	  case GUI_ID_BUTTON0: // Notifications sent by 'send'
		switch(NCode) 
		{
		  case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)
			
			// USER END
			break;
		  case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			SendMessage();
			if(IsSetList==0)
			{	
				SaveMessage(messageNumRows);
				messageNumRows++;
			}
			else					
				SaveMessage(messageindex);
			pContacts[0]='\0';
			pContent[0]='\0';
			EDIT_SetText(hContacts,pContacts);
			MULTIEDIT_SetText(hContent,'\0');			
			i=messageNumRows;
			while(i)
			{
				LISTVIEW_DeleteRow(hMessagelist,i-1);
				i--;
			}
			LISTVIEW_AddItem();
			IsSetList=0;
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
		}
      break;
	  case GUI_ID_BUTTON1: // Notifications sent by 'cancel'
		switch(NCode) 
		{
		  case WM_NOTIFICATION_CLICKED:
			// USER START (Optionally insert code for reacting on notification message)	
			IsSetList=0;
			// USER END
			break;
		  case WM_NOTIFICATION_RELEASED:
			// USER START (Optionally insert code for reacting on notification message)
			pContacts[0]='\0';
			pContent[0]='\0';
			EDIT_SetText(hContacts,pContacts);
			MULTIEDIT_SetText(hContent,'\0');	
			// USER END
			break;
			// USER START (Optionally insert additional code for further notification handling)
			// USER END
		}
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateMessage
*/
void OnICON11Clicked(void)
{
	OS_DEBUG("Messageapp create\n");
	GUI_CreateDialogBox(_aDialogCreateMessage, GUI_COUNTOF(_aDialogCreateMessage), _cbDialogMessage, WM_HBKWIN, 0, 0);
	
	/* 初始化并检测模块 */
	if (sim900a_init()!= 0)
	{
		GUI_MessageBox("\r\n No detected SIM900A module! \r\n","error",GUI_MESSAGEBOX_CF_MOVEABLE);
	}
	while(OnICON11)
	{
		GUI_Delay(10); 
	}
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
